columns:
- online_order
- book_table
- rate
- votes
- listed_in(type)
- cuisines
- cost
- listed_in(city)
- reviews_list

drop_columns:
- url
- address
- name
- phone
- location
- dish_liked
- rest_type
- menu_item

numerical_cols:
- votes
- cost
